### ISSUE TITLE
Handling JSON data

### ISSUE THREAD

**Issue by ian-lewis-d** [transferwise/pipelinewise-tap-mysql#165]
**I have several fields in a MySql database stored as JSON strings**

When extracting the data the JSON strings are not converted to Dict objects and are therefore unparseable later in the pipeline (for example if I wish to strip PII)

I have tried using the `schema` extra to convert the type of the field but it doesn't have an effect.

eg.
```
  config:
    plugins:
      extractors:
      - name: tap-mysql
        config:
          host: <host>
          user: <user>
          database: example
          ssl: true
        schema:
          example-table_name:
            json_data:
              type: ['null', object]
              format: object
```

How do you recommend I deal with this? 

My current pipeline is:

` meltano run tap-mysql hide-emails target-parquet`

Where `hide-emails` is defined as:

```
  - name: transform-field
    variant: transferwise
    pip_url: pipelinewise-transform-field
    mappings:
      - name: hide-emails
        config:
          transformations:
            - field_id: "json_data"
              tap_stream_name: "example-table_name"
              field_paths: [ "email" ]
              type: "HASH"

```

I can see that the transform has an effect as the _entire_ JSON string is hashed. 

With a Jupyter Notebook I have verified that the `transform-field` `do_transform` method works on my data but _only_ if I do a `json.loads()` first.
